name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache --push -t ping-pong-production-ecr:latest .

      - name: Deploy to ECS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 667332577260.dkr.ecr.eu-central-1.amazonaws.com/ping-pong-production-ecr
          aws ecs update-service --cluster ping-pong-production-cluster --service ping-pong-production-ecs-service --force-new-deployment
